### PR TITLE
Added table of contents to SUMMARY.md

### PR DESCRIPTION
**Pull request by mfliu**
Added a table of contents to the SUMMARY file and empty md files for the chapters and sections

### CODE REVIEW

**Review by pqz317 — APPROVED** [review]
Thanks for making this more organized!

**Comment by eywalker** [comment]
@Synicix actually reorganized the repo so that you don't have to generate and commit the website - just the src

**Comment by Synicix** [comment]
I added an automatic GitHub Action action to auto build the website and place it inside the docs folder. This was detailed in the README I already updated to reflect the code organization: https://github.com/learning-2-learn/learning-2-learn.github.io#building-docs

As such the only thing that should be committed after checking that it builds correctly on local copy is the .md in /src

@mfliu @pqz317

**Review by Synicix — CHANGES_REQUESTED** [review]
- Remove the l2l book build files.
- Could you rename the .md files to the topic of the page? Chapter_1 and etc. is not very descriptive and will make it a little pain to tracked down what page is what based on the file name.

**Comment by Synicix** [comment]
@mfliu Ah one thing, typically for commits message we just stick to imperative tense, like instead of adding just say added.

**Pull request merged**
